# Generated by Django 4.2.5 on 2023-09-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto_detalle',
            new_name='Producto',
        ),
    ]
