# Generated by Django 4.2.5 on 2023-09-29 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas1', '0002_rename_producto_detalle_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detalle_usuario',
        ),
    ]
