# Generated by Django 4.2.5 on 2023-09-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas1', '0004_carritocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.IntegerField(),
        ),
    ]
